### ISSUE TITLE
Redirect wildcard subdirectories

### ISSUE THREAD

**Issue by viet** [minecraftly/redirect#2]
Currently there's no redirect setup for m.ly/*

Can we make it redirect to https://minecraftly.com/*

**Comment by SilverCory** [comment]
Yes we can do that! Would this include the query? E.G the part like `?p=page` at the end of the url.

**Comment by viet** [comment]
Yes! Wildcard doesn't care about query string ;)

**Comment by viet** [comment]
I fixed this one,  no need to worry about it ;)

**Comment by SilverCory** [comment]
Ah sweet thanks.
